communicator_node:
  ros_parameters:
    robots:
      Husky1:
        type: Husky
        topics:
          odometry: /transformed_odom
          navigation:
            navigation_path: e.g. /transformed_global_plan
            navigation_status: e.g. /navigate_to_pose/_action/status
          feedback:
            robot_status: /husky/status

      Kobuki1:
        type: Kobuki
        topics:
          odometry: /odom
          navigation:
            navigation_path: /plan
            navigation_status: /navigate_to_pose/_action/status
          feedback:
            battery_state: /battery_state
            wheel_vel: /wheel_vels
            navigation_path: /plan 
            joint_states: /joint_states